apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dapr-dashboard
  namespace: dapr-system
spec:
  parentRefs:
  - name: gateway-dapr-dashboard
    sectionName: foobar
  hostnames:
  - "localhost"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: dapr-dashboard
      port: 8080