apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bearer-token
  namespace: openid-demo
spec:
  type: middleware.http.bearer
  version: v1
  metadata:
  - name: clientId
    value: "myclient"
  - name: issuerURL
    value: "https://dashboard.keycloak.127.0.0.1.nip.io/realms/demo"
  - name: jwksURL
    value: "https://dashboard.keycloak.127.0.0.1.nip.io/realms/demo/protocol/openid-connect/certs"