apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-keycloak
  namespace: keycloak
spec:
  tls:
    - hosts:
        - dashboard.keycloak.127.0.0.1.nip.io
  rules:
  - host: dashboard.keycloak.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
  ingressClassName: nginx