apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipelineoauthclientcred
spec:
  # tracing:
  #   samplingRate: "1"
  #   zipkin:
  #     endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
  httpPipeline:
    handlers:
    - type: middleware.http.oauth2clientcredentials
      name: oauth2client 
