apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2
spec:
  type: middleware.http.oauth2
  version: v1
  metadata:
  - name: clientId
    value: "dapr-oauth-demo"
  - name: clientSecret
    value: "JTkhrCxe9A95lm3rlwKP0P5HCp6rDg9Q"
  - name: scopes
    value: "openid profile"
  - name: authURL
    value: "https://40ed-49-36-24-37.ngrok-free.app/realms/demo/protocol/openid-connect/auth"
  - name: tokenURL
    value: "https://40ed-49-36-24-37.ngrok-free.app/realms/demo/protocol/openid-connect/token"
  - name: redirectURL
    value: "http://oauthecho-api.127.0.0.1.nip.io"
  - name: authHeaderName
    value: "authorization"
 