apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2
  namespace: oauth2
spec:
  type: middleware.http.oauth2
  version: v1
  metadata:
  - name: clientId
    value: "myclient"
  - name: clientSecret
    value: "cwqQpgHx4QzX7eN3jtzYrHPnJs83rvgu"
  - name: scopes
    value: "openid profile"
  - name: authURL
    value: "https://dashboard.keycloak.127.0.0.1.nip.io/realms/demo/protocol/openid-connect/auth"
  - name: tokenURL
    value: "https://dashboard.keycloak.127.0.0.1.nip.io/realms/demo/protocol/openid-connect/token"
  - name: redirectURL
    value: "http://oauthecho-api.127.0.0.1.nip.io/"
  - name: authHeaderName
    value: "authorization"
 