apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipelineoauth
  namespace: oauth2
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://dapr-dev-zipkin.default.svc.cluster.local:9411/api/v2/spans"
  httpPipeline:
    handlers:
    - type: middleware.http.oauth2
      name: oauth2    
